# Generated by Django 4.1.2 on 2022-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('farm_name', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
            ],
        ),
    ]
