# Generated by Django 4.1.2 on 2023-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('farm_name', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('percentage_crop', models.CharField(max_length=5)),
                ('image_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
